# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _kerrgeodesics
else:
    import _kerrgeodesics

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class korb_params(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    eccentric = property(_kerrgeodesics.korb_params_eccentric_get, _kerrgeodesics.korb_params_eccentric_set)
    inclined = property(_kerrgeodesics.korb_params_inclined_get, _kerrgeodesics.korb_params_inclined_set)
    a = property(_kerrgeodesics.korb_params_a_get, _kerrgeodesics.korb_params_a_set)
    p = property(_kerrgeodesics.korb_params_p_get, _kerrgeodesics.korb_params_p_set)
    e = property(_kerrgeodesics.korb_params_e_get, _kerrgeodesics.korb_params_e_set)
    x = property(_kerrgeodesics.korb_params_x_get, _kerrgeodesics.korb_params_x_set)
    thmin = property(_kerrgeodesics.korb_params_thmin_get, _kerrgeodesics.korb_params_thmin_set)
    E = property(_kerrgeodesics.korb_params_E_get, _kerrgeodesics.korb_params_E_set)
    Lz = property(_kerrgeodesics.korb_params_Lz_get, _kerrgeodesics.korb_params_Lz_set)
    Q = property(_kerrgeodesics.korb_params_Q_get, _kerrgeodesics.korb_params_Q_set)
    B = property(_kerrgeodesics.korb_params_B_get, _kerrgeodesics.korb_params_B_set)
    zm = property(_kerrgeodesics.korb_params_zm_get, _kerrgeodesics.korb_params_zm_set)
    zp = property(_kerrgeodesics.korb_params_zp_get, _kerrgeodesics.korb_params_zp_set)
    r1 = property(_kerrgeodesics.korb_params_r1_get, _kerrgeodesics.korb_params_r1_set)
    r2 = property(_kerrgeodesics.korb_params_r2_get, _kerrgeodesics.korb_params_r2_set)
    r3 = property(_kerrgeodesics.korb_params_r3_get, _kerrgeodesics.korb_params_r3_set)
    r4 = property(_kerrgeodesics.korb_params_r4_get, _kerrgeodesics.korb_params_r4_set)
    p3 = property(_kerrgeodesics.korb_params_p3_get, _kerrgeodesics.korb_params_p3_set)
    p4 = property(_kerrgeodesics.korb_params_p4_get, _kerrgeodesics.korb_params_p4_set)
    Vr = property(_kerrgeodesics.korb_params_Vr_get, _kerrgeodesics.korb_params_Vr_set)
    Vth = property(_kerrgeodesics.korb_params_Vth_get, _kerrgeodesics.korb_params_Vth_set)
    Yr = property(_kerrgeodesics.korb_params_Yr_get, _kerrgeodesics.korb_params_Yr_set)
    Yth = property(_kerrgeodesics.korb_params_Yth_get, _kerrgeodesics.korb_params_Yth_set)
    Yphi = property(_kerrgeodesics.korb_params_Yphi_get, _kerrgeodesics.korb_params_Yphi_set)
    Ga = property(_kerrgeodesics.korb_params_Ga_get, _kerrgeodesics.korb_params_Ga_set)
    wr = property(_kerrgeodesics.korb_params_wr_get, _kerrgeodesics.korb_params_wr_set)
    wth = property(_kerrgeodesics.korb_params_wth_get, _kerrgeodesics.korb_params_wth_set)
    wphi = property(_kerrgeodesics.korb_params_wphi_get, _kerrgeodesics.korb_params_wphi_set)
    dladpsinum = property(_kerrgeodesics.korb_params_dladpsinum_get, _kerrgeodesics.korb_params_dladpsinum_set)
    dladchinum = property(_kerrgeodesics.korb_params_dladchinum_get, _kerrgeodesics.korb_params_dladchinum_set)
    dpsidlanum = property(_kerrgeodesics.korb_params_dpsidlanum_get, _kerrgeodesics.korb_params_dpsidlanum_set)
    dchidlanum = property(_kerrgeodesics.korb_params_dchidlanum_get, _kerrgeodesics.korb_params_dchidlanum_set)
    Trnum = property(_kerrgeodesics.korb_params_Trnum_get, _kerrgeodesics.korb_params_Trnum_set)
    Tthnum = property(_kerrgeodesics.korb_params_Tthnum_get, _kerrgeodesics.korb_params_Tthnum_set)
    Prnum = property(_kerrgeodesics.korb_params_Prnum_get, _kerrgeodesics.korb_params_Prnum_set)
    Pthnum = property(_kerrgeodesics.korb_params_Pthnum_get, _kerrgeodesics.korb_params_Pthnum_set)
    err = property(_kerrgeodesics.korb_params_err_get, _kerrgeodesics.korb_params_err_set)

    def __init__(self):
        _kerrgeodesics.korb_params_swiginit(self, _kerrgeodesics.new_korb_params())
    __swig_destroy__ = _kerrgeodesics.delete_korb_params

# Register korb_params in _kerrgeodesics:
_kerrgeodesics.korb_params_swigregister(korb_params)

def korb_getparams(eccentric, inclined, a, p, e0, x0, err, orbpar):
    return _kerrgeodesics.korb_getparams(eccentric, inclined, a, p, e0, x0, err, orbpar)

def korb_freepar(orbpar):
    return _kerrgeodesics.korb_freepar(orbpar)

def korb_zfromchi(chi, orbpar):
    return _kerrgeodesics.korb_zfromchi(chi, orbpar)

def korb_thfromla(la, orbpar):
    return _kerrgeodesics.korb_thfromla(la, orbpar)

def korb_rfrompsi(psi, orbpar):
    return _kerrgeodesics.korb_rfrompsi(psi, orbpar)

def korb_dladchi(chi, orbpar):
    return _kerrgeodesics.korb_dladchi(chi, orbpar)

def korb_dladpsi(psi, orbpar):
    return _kerrgeodesics.korb_dladpsi(psi, orbpar)

def korb_dchidla(chi, orbpar):
    return _kerrgeodesics.korb_dchidla(chi, orbpar)

def korb_dpsidla(psi, orbpar):
    return _kerrgeodesics.korb_dpsidla(psi, orbpar)

def korb_lafrompsi(psi, orbpar):
    return _kerrgeodesics.korb_lafrompsi(psi, orbpar)

def korb_lafromchi(chi, orbpar):
    return _kerrgeodesics.korb_lafromchi(chi, orbpar)

def korb_D(r, orbpar):
    return _kerrgeodesics.korb_D(r, orbpar)

def korb_Tr(psi, orbpar):
    return _kerrgeodesics.korb_Tr(psi, orbpar)

def korb_Trint(psi, n, orbpar):
    return _kerrgeodesics.korb_Trint(psi, n, orbpar)

def korb_Tth(chi, orbpar):
    return _kerrgeodesics.korb_Tth(chi, orbpar)

def korb_Tthint(chi, n, orbpar):
    return _kerrgeodesics.korb_Tthint(chi, n, orbpar)

def korb_Pr(psi, orbpar):
    return _kerrgeodesics.korb_Pr(psi, orbpar)

def korb_Print(psi, n, orbpar):
    return _kerrgeodesics.korb_Print(psi, n, orbpar)

def korb_Pth(chi, orbpar):
    return _kerrgeodesics.korb_Pth(chi, orbpar)

def korb_Pthint(chi, n, orbpar):
    return _kerrgeodesics.korb_Pthint(chi, n, orbpar)

def korb_dchidlaint(chi, n, orbpar):
    return _kerrgeodesics.korb_dchidlaint(chi, n, orbpar)

def korb_dpsidlaint(psi, n, orbpar):
    return _kerrgeodesics.korb_dpsidlaint(psi, n, orbpar)

def korb_dtrfromla(la, orbpar):
    return _kerrgeodesics.korb_dtrfromla(la, orbpar)

def korb_dtthfromla(la, orbpar):
    return _kerrgeodesics.korb_dtthfromla(la, orbpar)

def korb_psifromla(la, orbpar):
    return _kerrgeodesics.korb_psifromla(la, orbpar)

def korb_chifromla(la, orbpar):
    return _kerrgeodesics.korb_chifromla(la, orbpar)

def korb_tfromla(la, orbpar):
    return _kerrgeodesics.korb_tfromla(la, orbpar)

def korb_dphirfromla(la, orbpar):
    return _kerrgeodesics.korb_dphirfromla(la, orbpar)

def korb_dphithfromla(la, orbpar):
    return _kerrgeodesics.korb_dphithfromla(la, orbpar)

def korb_phifromla(la, orbpar):
    return _kerrgeodesics.korb_phifromla(la, orbpar)

def korb_drsdr(rm, a):
    return _kerrgeodesics.korb_drsdr(rm, a)

def korb_rsfromrsubtrplus(rsubtrplus, a):
    return _kerrgeodesics.korb_rsfromrsubtrplus(rsubtrplus, a)

def korb_rsubtrplusfromrs(rs, a):
    return _kerrgeodesics.korb_rsubtrplusfromrs(rs, a)

